_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_field: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_display_mode: 0
  entity_extra_field: 0
  entity_extra_field_ui: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  google_tag: 0
  help: 0
  history: 0
  iframe: 0
  image: 0
  inline_entity_form: 0
  jquery_ui: 0
  jquery_ui_accordion: 0
  link: 0
  link_url_decoder: 0
  media: 0
  media_entity_download: 0
  menu_link_content: 0
  menu_ui: 0
  module_filter: 0
  node: 0
  notification_message: 0
  options: 0
  page_cache: 0
  paragraphs_jquery_ui_accordion: 0
  path: 0
  path_alias: 0
  rdf: 0
  rebuild_cache_access: 0
  redirect: 0
  search: 0
  shortcut: 0
  social_media_links: 0
  social_media_links_field: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  view_unpublished: 0
  views_autosubmit: 0
  views_ui: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  bartik: 0
  seven: 0
  stable: 0
  limitless: 0
profile: standard
